[package]
name = "rust-webcam"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"

[lints.rust]
unused = "allow"

[dependencies.nokhwa]
version = "0.10.0"
# Use the native input backends, enable WGPU integration
features = ["input-native", "output-wgpu"]
